select * from customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers
 
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
LIMIT 20;

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, AVG(review_rating) AS "Average_Product_Rating" -- average is double precision datatype
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average purchase amounts between Standard and Express Shipping

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
COUNT(customer_id) AS "Total Customers",
ROUND(AVG(purchase_amount),2) AS "Average Amount", 
SUM(purchase_amount) AS "Total Revenue"
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest previous purchases with discounts applied?

SELECT item_purchased FROM customer
WHERE discount_applied ='Yes'
ORDER BY previous_purchases DESC
LIMIT 5;

--Q7. Which 5 products have the highest PERCENTAGE of purchases with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q8. Segment customers into New, Returning(2-10), and Loyal(>10) based on their total number of previous purchases 
-- and show the count of each segment #Customer Segmentation concept

WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases between 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(customer_id) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q9. What are the TOP 3 MOST PURCHASED PRODUCTS within each category?

WITH popular_products AS
(
SELECT 
category, item_purchased, COUNT(*) AS "Total Purchases",
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, "Total Purchases"
FROM popular_products
WHERE item_rank <=3
ORDER BY category, item_rank;

--Q10. Are customers who are repeat buyers (more than 5 previous_purchases) most likely to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q11. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;
